from dataclasses import dataclass, replace


@dataclass(frozen=True)
class TableSpec:
    name: str
    layer: str
    columns: tuple[str, ...]
    key_type: str = "UNIQUE"
    key_columns: tuple[str, ...] = ()
    partition_column: str = ""


DORIS_TABLES: dict[str, TableSpec] = {
    "ods_api_yunting_service_page_log_d": TableSpec(
        "ods_api_yunting_service_page_log_d",
        "ods",
        (
            "run_id",
            "page_no",
            "request_body_json",
            "response_code",
            "response_msg",
            "trace_id",
            "has_more",
            "page_token_hash",
            "raw_file_path",
            "source_system",
            "create_time",
            "update_time",
            "dt",
        ),
    ),
    "ods_api_yunting_service_session_raw_f_d": TableSpec(
        "ods_api_yunting_service_session_raw_f_d",
        "ods",
        (
            "unique_id",
            "run_id",
            "insert_timestamp",
            "source_name",
            "project_name",
            "category_id",
            "raw_json",
            "raw_json_hash",
            "raw_file_path",
            "source_system",
            "create_time",
            "update_time",
            "dt",
        ),
    ),
    "std_api_yunting_service_session_f_d": TableSpec(
        "std_api_yunting_service_session_f_d",
        "std",
        (
            "unique_id",
            "oid",
            "project_name",
            "source_name",
            "shop_name",
            "session_type",
            "session_start_time",
            "session_close_time",
            "user_id",
            "user_name",
            "server_name_list_json",
            "order_no_list_json",
            "escore",
            "score",
            "is_default",
            "category_id",
            "contents_json",
            "topic_configs_json",
            "tag_list_json",
            "raw_file_path",
            "source_system",
            "biz_create_time",
            "biz_update_time",
            "create_time",
            "update_time",
            "dt",
        ),
    ),
    "std_api_yunting_service_message_f_d": TableSpec(
        "std_api_yunting_service_message_f_d",
        "std",
        (
            "message_pk",
            "content_id",
            "unique_id",
            "message_index",
            "publish_time",
            "role",
            "message_type",
            "user_name",
            "content_text",
            "product_title_list_json",
            "raw_json",
            "source_system",
            "create_time",
            "update_time",
            "dt",
        ),
    ),
    "std_api_yunting_service_media_asset_f_d": TableSpec(
        "std_api_yunting_service_media_asset_f_d",
        "std",
        (
            "asset_id",
            "unique_id",
            "content_id",
            "message_type",
            "role",
            "source_url",
            "content_type",
            "file_sha256",
            "file_size",
            "download_status",
            "media_object_key",
            "error_message",
            "source_system",
            "create_time",
            "update_time",
            "dt",
        ),
    ),
    "dwd_api_yunting_service_session_f_d": TableSpec(
        "dwd_api_yunting_service_session_f_d",
        "dwd",
        (
            "unique_id",
            "oid",
            "project_name",
            "source_name",
            "shop_name",
            "session_type",
            "session_start_time",
            "session_close_time",
            "user_id",
            "user_name",
            "server_name_list_json",
            "order_no_list_json",
            "escore",
            "score",
            "is_default",
            "category_id",
            "contents_json",
            "topic_configs_json",
            "tag_list_json",
            "raw_file_path",
            "source_system",
            "biz_create_time",
            "biz_update_time",
            "create_time",
            "update_time",
            "dt",
            "source_type",
        ),
    ),
    "dwd_api_yunting_service_message_f_d": TableSpec(
        "dwd_api_yunting_service_message_f_d",
        "dwd",
        (
            "message_pk",
            "content_id",
            "unique_id",
            "message_index",
            "publish_time",
            "role",
            "message_type",
            "user_name",
            "content_text",
            "product_title_list_json",
            "raw_json",
            "source_system",
            "create_time",
            "update_time",
            "dt",
            "source_type",
        ),
    ),
    "dwd_api_yunting_service_media_asset_f_d": TableSpec(
        "dwd_api_yunting_service_media_asset_f_d",
        "dwd",
        (
            "asset_id",
            "unique_id",
            "content_id",
            "message_type",
            "role",
            "source_url",
            "content_type",
            "file_sha256",
            "file_size",
            "download_status",
            "media_object_key",
            "error_message",
            "source_system",
            "create_time",
            "update_time",
            "dt",
            "source_type",
        ),
    ),
    "dim_yunting_topic_value": TableSpec(
        "dim_yunting_topic_value",
        "dim",
        ("unique_id", "topic_name", "topic_value_hash", "topic_value", "source_system", "create_time", "update_time", "dt"),
    ),
    "dim_yunting_tag": TableSpec(
        "dim_yunting_tag",
        "dim",
        ("unique_id", "tag_name", "tag_escore", "topic_configs_json", "source_system", "create_time", "update_time", "dt"),
    ),
    "dim_yunting_service_enum": TableSpec(
        "dim_yunting_service_enum",
        "dim",
        ("enum_type", "enum_code", "enum_name", "source_system", "create_time", "update_time", "dt"),
    ),
    "dws_yunting_service_faq_case_d": TableSpec(
        "dws_yunting_service_faq_case_d",
        "dws",
        (
            "case_id",
            "unique_id",
            "case_title",
            "customer_question_summary",
            "answer_summary",
            "symptom_summary",
            "resolution_summary",
            "product_summary",
            "brand_json",
            "sku_json",
            "spu_json",
            "product_name_json",
            "tags_json",
            "topic_values_json",
            "evidence_level",
            "source_type",
            "reference_class",
            "authority_level",
            "authority_score",
            "can_be_reference",
            "quality_status",
            "source_name",
            "shop_name",
            "session_type",
            "stat_date",
            "stat_week",
            "create_time",
            "update_time",
        ),
    ),
    "dws_yunting_service_faq_chunk_d": TableSpec(
        "dws_yunting_service_faq_chunk_d",
        "dws",
        (
            "chunk_id",
            "case_id",
            "unique_id",
            "chunk_type",
            "chunk_text",
            "question",
            "answer",
            "source_content_ids_json",
            "linked_asset_ids_json",
            "embedding_text_hash",
            "quality_status",
            "source_type",
            "reference_class",
            "authority_level",
            "authority_score",
            "can_be_reference",
            "stat_date",
            "stat_week",
            "create_time",
            "update_time",
        ),
    ),
    "dws_yunting_service_media_observation_d": TableSpec(
        "dws_yunting_service_media_observation_d",
        "dws",
        (
            "media_chunk_id",
            "asset_id",
            "unique_id",
            "content_id",
            "message_type",
            "ocr_text",
            "visual_summary",
            "video_summary",
            "keyframe_refs_json",
            "evidence_level",
            "source_type",
            "reference_class",
            "authority_level",
            "authority_score",
            "can_be_reference",
            "stat_date",
            "stat_week",
            "create_time",
            "update_time",
        ),
    ),
    "ads_agent_yunting_faq_vector_api_d": TableSpec(
        "ads_agent_yunting_faq_vector_api_d",
        "ads",
        (
            "point_id",
            "collection_name",
            "chunk_id",
            "case_id",
            "unique_id",
            "vector_model",
            "vector_dimension",
            "payload_json",
            "payload_hash",
            "embedding_text",
            "embedding_text_hash",
            "sync_status",
            "last_synced_at",
            "error_message",
            "stat_date",
            "stat_week",
            "create_time",
            "update_time",
        ),
    ),
    "ads_agent_yunting_media_vector_api_d": TableSpec(
        "ads_agent_yunting_media_vector_api_d",
        "ads",
        (
            "point_id",
            "collection_name",
            "media_chunk_id",
            "asset_id",
            "unique_id",
            "vector_model",
            "vector_dimension",
            "payload_json",
            "media_object_key",
            "sync_status",
            "last_synced_at",
            "error_message",
            "stat_date",
            "stat_week",
            "create_time",
            "update_time",
        ),
    ),
    "ads_agent_yunting_pipeline_dashboard_d": TableSpec(
        "ads_agent_yunting_pipeline_dashboard_d",
        "ads",
        (
            "stat_date",
            "run_id",
            "stat_week",
            "api_page_count",
            "raw_session_count",
            "std_session_count",
            "valid_case_count",
            "faq_chunk_count",
            "media_asset_count",
            "download_success_count",
            "embedding_success_count",
            "qdrant_upsert_success_count",
            "failed_count",
            "create_time",
            "update_time",
        ),
    ),
    "dm_yunting_service_quality_d": TableSpec(
        "dm_yunting_service_quality_d",
        "dm",
        (
            "stat_date",
            "stat_week",
            "source_type",
            "session_count",
            "valid_case_count",
            "message_count",
            "customer_message_count",
            "server_message_count",
            "reference_class",
            "authority_level",
            "create_time",
            "update_time",
        ),
    ),
    "dm_yunting_service_product_tag_d": TableSpec(
        "dm_yunting_service_product_tag_d",
        "dm",
        (
            "stat_date",
            "stat_week",
            "source_type",
            "topic_value_count",
            "tag_count",
            "faq_count",
            "media_evidence_count",
            "create_time",
            "update_time",
        ),
    ),
    "dm_yunting_service_media_d": TableSpec(
        "dm_yunting_service_media_d",
        "dm",
        (
            "stat_date",
            "stat_week",
            "source_type",
            "image_count",
            "video_count",
            "download_success_count",
            "ocr_success_count",
            "visual_summary_success_count",
            "media_upsert_success_count",
            "create_time",
            "update_time",
        ),
    ),
}


LAYER_ORDER = ("ods", "std", "dwd", "dim", "dws", "ads", "dm")


TABLE_KEY_COLUMNS: dict[str, tuple[str, ...]] = {
    "ods_api_yunting_service_page_log_d": ("run_id", "page_no"),
    "ods_api_yunting_service_session_raw_f_d": ("unique_id",),
    "std_api_yunting_service_session_f_d": ("unique_id",),
    "std_api_yunting_service_message_f_d": ("message_pk",),
    "std_api_yunting_service_media_asset_f_d": ("asset_id",),
    "dwd_api_yunting_service_session_f_d": ("unique_id",),
    "dwd_api_yunting_service_message_f_d": ("message_pk",),
    "dwd_api_yunting_service_media_asset_f_d": ("asset_id",),
    "dim_yunting_topic_value": ("unique_id", "topic_name", "topic_value_hash"),
    "dim_yunting_tag": ("unique_id", "tag_name"),
    "dim_yunting_service_enum": ("enum_type", "enum_code"),
    "dws_yunting_service_faq_case_d": ("case_id",),
    "dws_yunting_service_faq_chunk_d": ("chunk_id",),
    "dws_yunting_service_media_observation_d": ("media_chunk_id",),
    "ads_agent_yunting_faq_vector_api_d": ("point_id",),
    "ads_agent_yunting_media_vector_api_d": ("point_id",),
    "ads_agent_yunting_pipeline_dashboard_d": ("stat_date", "run_id"),
    "dm_yunting_service_quality_d": ("stat_date", "stat_week", "source_type"),
    "dm_yunting_service_product_tag_d": ("stat_date", "stat_week", "source_type"),
    "dm_yunting_service_media_d": ("stat_date", "stat_week", "source_type"),
}


TABLE_PARTITION_COLUMNS: dict[str, str] = {
    table_name: ("dt" if spec.layer in {"ods", "std", "dwd", "dim"} else "stat_date")
    for table_name, spec in DORIS_TABLES.items()
}


DORIS_TABLES = {
    table_name: replace(
        spec,
        key_type="UNIQUE",
        key_columns=TABLE_KEY_COLUMNS[table_name],
        partition_column=TABLE_PARTITION_COLUMNS[table_name],
    )
    for table_name, spec in DORIS_TABLES.items()
}
